'use client'
import { useMemo, useState, type ReactNode } from 'react'
import Link from 'next/link'
import type { Pick2MlbValueBoardContract } from '@/types/pick2-value-board'
import { OpportunityCard } from './MlbCards'
import { displayStatuses, presentationStatus, labels, type MlbGame, type DisplayStatus } from './mlb-presentation'
const control = 'w-full min-w-0 rounded-lg border border-slate-600 bg-slate-950 px-3 py-2.5 text-sm text-slate-100 focus-visible:outline-2 focus-visible:outline-teal-300'
const defaults = { status: 'ALL', team: '', side: 'ALL', book: '', start: '', minEdge: '', minEv: '', freshness: '', starter: '' }
export default function MlbValueBoardClient({ board, games = [] }: { board: Pick2MlbValueBoardContract; games?: MlbGame[] }) {
 const [filters, setFilters] = useState(defaults)
 const update = (key: keyof typeof filters, value: string) => setFilters(f => ({ ...f, [key]: value }))
 const counts = useMemo(() => Object.fromEntries(displayStatuses.map(s => [s, board.rows.filter(r => presentationStatus(r) === s).length])) as Record<DisplayStatus, number>, [board.rows])
 const rows = useMemo(() => board.rows.filter(r => {
 const start = r.start_time ? new Intl.DateTimeFormat('en-GB', { timeZone: 'America/Puerto_Rico', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).format(new Date(r.start_time)) : ''
 return (filters.status === 'ALL' || presentationStatus(r) === filters.status) && (!filters.team || (r.home_team + ' ' + r.away_team).toLowerCase().includes(filters.team.toLowerCase())) && (filters.side === 'ALL' || r.side === filters.side) && (!filters.book || r.best_book === filters.book) && (!filters.start || start >= filters.start) && (!filters.minEdge || r.consensus_edge >= Number(filters.minEdge) / 100) && (!filters.minEv || r.unit_ev >= Number(filters.minEv) / 100) && (!filters.freshness || r.market_freshness === filters.freshness) && (!filters.starter || r.starter_status === filters.starter)
 }).sort((a, b) => displayStatuses.indexOf(presentationStatus(a)) - displayStatuses.indexOf(presentationStatus(b)) || a.board_rank - b.board_rank), [board.rows, filters])
 const waitingGames = games.filter(g => g.reason && !board.rows.some(r => r.game_pk === g.gamePk)).length
 const books = [...new Set(board.rows.map(r => r.best_book))].sort()
 return <div className="mlb-ui mx-auto max-w-7xl space-y-6">
 <header><p className="text-xs font-semibold uppercase tracking-[0.2em] text-teal-300">MLB | Moneyline analysis</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Value Board</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-300">Compare the probability with the price. Official Picks lead; other opportunities keep their own place.</p></header>
 <section aria-label="Opportunity summary" className="grid grid-cols-2 gap-3 lg:grid-cols-5">{displayStatuses.map(s => <button key={s} type="button" aria-pressed={filters.status === s} onClick={() => update('status', filters.status === s ? 'ALL' : s)} className="rounded-xl border border-slate-700 bg-slate-900 p-4 text-left hover:border-teal-300 focus-visible:outline-2 focus-visible:outline-teal-300"><span className="text-xs text-slate-300">{s === 'OFFICIAL_PICK' ? 'Official Picks' : s === 'VALUE_CANDIDATE' ? 'Value Candidates' : labels[s]}</span><span data-summary={s} className="mt-2 block text-3xl font-semibold tabular-nums text-white">{counts[s]}</span></button>)}</section>
 <p className="text-xs leading-5 text-slate-400">Counts are side-level opportunities, not games.{waitingGames > 0 && <> {waitingGames} additional games await analysis on <Link className="underline" href="/today">Today</Link>.</>} No Edge is separate from Watchlist.</p>
 {counts.OFFICIAL_PICK + counts.VALUE_CANDIDATE === 0 && <div role="status" className="rounded-xl border border-slate-700 p-5"><h2 className="font-semibold">No qualifying plays right now</h2><p className="mt-2 text-sm text-slate-300">{counts.NO_EDGE > 0 ? 'Some prices offer no positive edge. ' : ''}{counts.BLOCKED + waitingGames > 0 ? 'Some games or opportunities are waiting for evidence, fresh odds or pregame eligibility.' : 'No current opportunity meets the Official Pick or Value Candidate criteria.'}</p></div>}
 <section aria-label="Filter opportunities" className="rounded-2xl border border-slate-700 bg-slate-900/60 p-5"><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">
 <Control label="Status"><select className={control} value={filters.status} onChange={e => update('status', e.target.value)}><option value="ALL">All classifications</option>{displayStatuses.map(s => <option key={s} value={s}>{labels[s]}</option>)}</select></Control>
 <Control label="Team"><input className={control} placeholder="Find a team" value={filters.team} onChange={e => update('team', e.target.value)} /></Control>
 <Control label="Side"><select className={control} value={filters.side} onChange={e => update('side', e.target.value)}><option value="ALL">Both sides</option><option value="AWAY">Away</option><option value="HOME">Home</option></select></Control>
 <Control label="Book"><select className={control} value={filters.book} onChange={e => update('book', e.target.value)}><option value="">All books</option>{books.map(b => <option key={b}>{b}</option>)}</select></Control>
 <Control label="Starts after (PR)"><input className={control} type="time" value={filters.start} onChange={e => update('start', e.target.value)} /></Control>
 <Control label="Minimum edge %"><input className={control} type="number" step="any" value={filters.minEdge} onChange={e => update('minEdge', e.target.value)} /></Control>
 <Control label="Minimum EV %"><input className={control} type="number" step="any" value={filters.minEv} onChange={e => update('minEv', e.target.value)} /></Control>
 <div className="flex items-end"><button type="button" className={control} onClick={() => setFilters(defaults)}>Clear filters</button></div>
 </div><details className="mt-4 text-sm text-slate-300"><summary className="cursor-pointer py-2 focus-visible:outline-2 focus-visible:outline-teal-300">Advanced Filters</summary><div className="mt-3 grid gap-4 sm:grid-cols-2"><Control label="Odds freshness"><select className={control} value={filters.freshness} onChange={e => update('freshness', e.target.value)}><option value="">Any freshness</option>{[...new Set(board.rows.map(r => r.market_freshness))].map(f => <option key={f} value={f}>{f === 'FRESH' ? 'Current odds' : f === 'GAME_STARTED' ? 'Pregame odds locked' : 'Waiting for fresh odds'}</option>)}</select></Control><Control label="Starter evidence"><select className={control} value={filters.starter} onChange={e => update('starter', e.target.value)}><option value="">Any starter evidence</option>{[...new Set(board.rows.map(r => r.starter_status))].map(s => <option key={s} value={s}>{/CONFIRMED|PROBABLE/.test(s) ? 'Starter available' : 'Starter evidence pending'}</option>)}</select></Control></div></details></section>
 <p role="status" className="text-sm text-slate-400">{rows.length} of {board.rows.length} opportunities</p>
 {rows.length ? displayStatuses.map(s => { const section = rows.filter(r => presentationStatus(r) === s); return section.length ? <section key={s} aria-label={labels[s]}><h2 className="mb-3 text-lg font-semibold">{labels[s]} <span className="ml-2 text-sm font-normal text-slate-400">{section.length}</span></h2><div className="grid items-start gap-4 lg:grid-cols-2">{section.map(r => <OpportunityCard key={r.game_pk + ':' + r.side} row={r} game={games.find(g => g.gamePk === r.game_pk)} />)}</div></section> : null }) : <div className="rounded-xl border border-slate-700 p-6 text-sm text-slate-300">{board.rows.length ? 'No opportunities match these filters. Try clearing a filter.' : 'Waiting for current game analysis and market prices. Check Today for game progress.'}</div>}
 <p className="text-xs leading-5 text-slate-400">All times Puerto Rico. Prices are snapshots. A higher probability is not always better value. Official Picks are not guaranteed winners. No historical profitability claim is made.</p>
 </div>
}
function Control({ label, children }: { label: string; children: ReactNode }) { return <label className="grid min-w-0 gap-2 text-xs text-slate-300">{label}{children}</label> }
