import 'server-only'

import { PRODUCT_STATUSES, type ProductStatus } from '@/config/product-status'
import type { SportsCenterReport, SportsCenterSport, SportsCenterSportKey } from '@/types/sports-center'

function capability(label: string, status: ProductStatus, route: string | null, summary: string) {
  return { label, status, route, summary }
}

const SPORTS_CENTER_SPORTS: SportsCenterSport[] = [
  {
    key: 'mlb',
    sportKey: 'baseball_mlb',
    label: 'MLB',
    status: 'Production',
    productReadiness: 'Production limited with certified projection-only and current-board surfaces.',
    dataState: 'Certified',
    modelState: 'Certified',
    todayState: 'Production',
    summary: 'MLB is the primary certified sport. Existing Current Board, Probability Picks, player projections, performance and operations surfaces remain canonical.',
    currentHealth: 'Use Current Board and AI Briefing for live daily readiness.',
    dataFreshness: 'Stored timestamps are shown on the underlying product pages.',
    providerHealth: 'No provider call is made by Sports Center.',
    todaysGames: 'Available through Dashboard Today and Current Board when stored rows exist.',
    settlementPipeline: 'Existing settlement and performance pages remain the source of truth; Sports Center does not modify settlement flow.',
    certifiedSurfaces: ['/dashboard', '/probability-picks', '/player-projections', '/performance', '/mlb-operations'],
    hiddenSurfaces: [
      capability('MLB operations', 'Production', '/mlb-operations', 'Operational MLB diagnostics already exist and are now easier to discover.'),
      capability('Player projections', 'Certified', '/player-projections', 'Projection Only / No Recommendation player view with prop-market comparison empty states.'),
    ],
    capabilities: [
      capability('Current Board', 'Production', '/dashboard', 'Primary daily board and product status summary.'),
      capability('Probability Picks', 'Certified', '/probability-picks', 'Projection-only ranking for eligible MLB rows.'),
      capability('Performance', 'Production', '/performance', 'Model accountability over stored history.'),
      capability('Player Props', 'Foundation', '/player-projections', 'Genuine stored prop rows are shown only when same-event projection identity exists.'),
    ],
    blockers: ['Full historical completion still requires approved imports and no retrospective projection generation.'],
    nextAction: 'Use AI Briefing or Current Board for today; use Player Projections for projection-only player review.',
  },
  {
    key: 'nba',
    sportKey: 'basketball_nba',
    label: 'NBA',
    status: 'Foundation',
    productReadiness: 'Partial/trial data foundation only; not production-pick eligible.',
    dataState: 'Foundation',
    modelState: 'Blocked',
    todayState: 'Blocked',
    summary: 'NBA has readiness and trial-isolation evidence, but production prediction activation remains blocked.',
    currentHealth: 'Readiness evidence is available through data-foundation and SportsDataIO NBA routes.',
    dataFreshness: 'Foundation routes report stored-data state; no live provider check is triggered here.',
    providerHealth: 'Provider execution remains gated by entitlement, migration and explicit approval.',
    todaysGames: 'No certified production Today surface is active for NBA.',
    settlementPipeline: 'Legacy/trial rows stay isolated from production settlement and performance claims.',
    certifiedSurfaces: ['/api/data-foundation/nba', '/api/providers/sportsdataio/nba/readiness'],
    hiddenSurfaces: [
      capability('NBA readiness', 'Foundation', '/api/providers/sportsdataio/nba/readiness', 'Aggregate zero-call readiness route for provider and domain gates.'),
    ],
    capabilities: [
      capability('Data foundation', 'Foundation', '/api/data-foundation/nba', 'Stored-data audit and blocker summary.'),
      capability('Production picks', 'Blocked', null, 'Blocked until sport-specific certification and data gates pass.'),
    ],
    blockers: ['Canonical results, full stats, odds, injuries and production prediction certification remain incomplete.'],
    nextAction: 'Keep NBA in foundation review until approved imports and certification gates are complete.',
  },
  {
    key: 'nfl',
    sportKey: 'americanfootball_nfl',
    label: 'NFL',
    status: 'Preview',
    productReadiness: 'Preview predictions active; production prediction and recommendation eligibility remain blocked.',
    dataState: 'Foundation',
    modelState: 'Preview',
    todayState: 'Blocked',
    summary: 'NFL has certified persisted Preview prediction evidence: 776 Preview rows and 776 feature snapshots, with zero Production rows and zero Official Picks.',
    currentHealth: 'Preview prediction lifecycle evidence exists; production state remains blocked until sport-specific production certification passes.',
    dataFreshness: 'Preview evidence is persisted; no certified production current NFL feed is active.',
    providerHealth: 'Provider calls are not authorized from this hub.',
    todaysGames: 'No certified production Today surface is active for NFL.',
    settlementPipeline: 'No active production settlement or recommendation claim for NFL.',
    certifiedSurfaces: ['/api/data-foundation/nfl', '/api/nfl/predictions/health', '/api/nfl/predictions/validation'],
    hiddenSurfaces: [capability('NFL preview lifecycle', 'Preview', '/api/nfl/predictions/validation', 'Read-only Preview prediction lifecycle validation route.')],
    capabilities: [
      capability('Preview predictions', 'Preview', '/api/nfl/predictions', 'Persisted Preview predictions exist and remain isolated from production recommendations.'),
      capability('Production predictions', 'Blocked', null, 'Blocked until production certification passes.'),
      capability('Recommendations', 'Blocked', null, 'Blocked; zero Official Picks are certified.'),
    ],
    blockers: ['Production prediction certification, recommendation eligibility and Official Pick certification remain blocked.'],
    nextAction: 'Keep NFL in Preview until production and recommendation certification gates pass.',
  },
  {
    key: 'soccer',
    sportKey: 'soccer',
    label: 'Soccer',
    status: 'Planning',
    productReadiness: 'Competition-specific planning only.',
    dataState: 'Planning',
    modelState: 'Blocked',
    todayState: 'Blocked',
    summary: 'Soccer must be scoped by competition and season; no global soccer readiness claim is made.',
    currentHealth: 'Foundation route preserves competition-specific governance.',
    dataFreshness: 'No certified competition feed is active.',
    providerHealth: 'Provider transport remains blocked without scoped competition approval.',
    todaysGames: 'Unavailable until a specific competition is approved and certified.',
    settlementPipeline: 'No active production settlement claim for soccer.',
    certifiedSurfaces: ['/api/data-foundation/soccer'],
    hiddenSurfaces: [capability('Soccer foundation', 'Planning', '/api/data-foundation/soccer', 'Competition-specific readiness route.')],
    capabilities: [capability('Competition governance', 'Planning', null, 'Requires explicit competition, season and source scope.')],
    blockers: ['No approved competition scope, stored coverage or certified prediction engine.'],
    nextAction: 'Choose one competition and run a future approved data-foundation gate.',
  },
  {
    key: 'bsn',
    sportKey: 'basketball_bsn',
    label: 'BSN',
    status: 'Preview',
    productReadiness: 'Partial custom-league foundation with manual/CSV readiness.',
    dataState: 'Foundation',
    modelState: 'Preview',
    todayState: 'Preview',
    summary: 'BSN remains useful for custom-league readiness review, but incomplete source coverage blocks full production claims.',
    currentHealth: 'Foundation evidence is available through the BSN data route.',
    dataFreshness: 'Manual/CSV source freshness must be verified in the underlying workflow.',
    providerHealth: 'No live provider dependency is invoked by Sports Center.',
    todaysGames: 'Preview only; use certified surfaces before treating any game as current production evidence.',
    settlementPipeline: 'Settlement claims remain limited by incomplete result and source coverage.',
    certifiedSurfaces: ['/api/data-foundation/bsn'],
    hiddenSurfaces: [capability('BSN foundation', 'Preview', '/api/data-foundation/bsn', 'Partial custom-league readiness route.')],
    capabilities: [capability('Manual import contract', 'Foundation', null, 'CSV/manual source contracts exist but require approved execution.')],
    blockers: ['Results, stats, boxscores, injuries, lineups, odds and props remain incomplete or unavailable.'],
    nextAction: 'Keep BSN as preview/foundation until source-complete imports are approved and certified.',
  },
  {
    key: 'nhl',
    sportKey: 'icehockey_nhl',
    label: 'NHL',
    status: 'Preview',
    productReadiness: 'Preview predictions active; production prediction and recommendation eligibility remain blocked.',
    dataState: 'Foundation',
    modelState: 'Preview',
    todayState: 'Blocked',
    summary: 'NHL has certified persisted Preview prediction evidence: 258 Preview rows and 258 feature snapshots, with zero Production rows and zero Official Picks.',
    currentHealth: 'Preview prediction lifecycle evidence exists; production state remains blocked until sport-specific production certification passes.',
    dataFreshness: 'Preview evidence is persisted; no certified production current NHL feed is active.',
    providerHealth: 'Provider execution remains blocked.',
    todaysGames: 'No certified production Today surface is active for NHL.',
    settlementPipeline: 'No active production settlement or recommendation claim for NHL.',
    certifiedSurfaces: ['/api/data-foundation/nhl', '/api/nhl/predictions/health', '/api/nhl/predictions/validation'],
    hiddenSurfaces: [capability('NHL preview lifecycle', 'Preview', '/api/nhl/predictions/validation', 'Read-only Preview prediction lifecycle validation route.')],
    capabilities: [
      capability('Preview predictions', 'Preview', '/api/nhl/predictions', 'Persisted Preview predictions exist and remain isolated from production recommendations.'),
      capability('Production predictions', 'Blocked', null, 'Blocked until production certification passes.'),
      capability('Recommendations', 'Blocked', null, 'Blocked; zero Official Picks are certified.'),
    ],
    blockers: ['Production prediction certification, recommendation eligibility and Official Pick certification remain blocked.'],
    nextAction: 'Keep NHL in Preview until production and recommendation certification gates pass.',
  },
  {
    key: 'tennis',
    sportKey: 'tennis',
    label: 'Tennis',
    status: 'Blocked',
    productReadiness: 'Event-driven blocked readiness domain.',
    dataState: 'Blocked',
    modelState: 'Blocked',
    todayState: 'Blocked',
    summary: 'Tennis is explicitly event-driven and must not be forced into team-season workflows.',
    currentHealth: 'Shared Tennis/UFC foundation route documents the blocker state.',
    dataFreshness: 'No certified event feed is active.',
    providerHealth: 'Provider execution is not authorized.',
    todaysGames: 'Unavailable until event source and prediction certification exist.',
    settlementPipeline: 'No active production settlement claim for Tennis.',
    certifiedSurfaces: ['/api/data-foundation/tennis-ufc'],
    hiddenSurfaces: [capability('Tennis/UFC readiness', 'Blocked', '/api/data-foundation/tennis-ufc', 'Event-driven readiness route.')],
    capabilities: [capability('Event-driven governance', 'Planning', null, 'Future event model only; no production picks.')],
    blockers: ['No certified event source, stored results, market data or prediction engine.'],
    nextAction: 'Keep Tennis blocked until an event-specific source and certification gate are approved.',
  },
  {
    key: 'ufc',
    sportKey: 'mma_ufc',
    label: 'UFC',
    status: 'Blocked',
    productReadiness: 'Event-driven blocked readiness domain.',
    dataState: 'Blocked',
    modelState: 'Blocked',
    todayState: 'Blocked',
    summary: 'UFC readiness is event-specific; no production pick or market surface is active.',
    currentHealth: 'Shared Tennis/UFC foundation route documents the blocker state.',
    dataFreshness: 'No certified event feed is active.',
    providerHealth: 'Provider execution is not authorized.',
    todaysGames: 'Unavailable until event source and prediction certification exist.',
    settlementPipeline: 'No active production settlement claim for UFC.',
    certifiedSurfaces: ['/api/data-foundation/tennis-ufc'],
    hiddenSurfaces: [capability('Tennis/UFC readiness', 'Blocked', '/api/data-foundation/tennis-ufc', 'Event-driven readiness route.')],
    capabilities: [capability('Fight-card governance', 'Planning', null, 'Future event model only; no production picks.')],
    blockers: ['No certified fight-card source, stored results, market data or prediction engine.'],
    nextAction: 'Keep UFC blocked until an event-specific source and certification gate are approved.',
  },
]

export function getSportsCenterReport(): SportsCenterReport {
  return {
    mode: 'sports_center_v1',
    generatedAt: new Date().toISOString(),
    readOnly: true,
    providerCallsMade: 0,
    remoteMutationsMade: 0,
    productionMutationsMade: 0,
    sports: SPORTS_CENTER_SPORTS,
    navigation: {
      topLevelRoute: '/sports-center',
      detailRoutePattern: '/sports-center/[sport]',
      exposedInDashboardShell: true,
      canonicalStatusSystem: [...PRODUCT_STATUSES],
    },
    settlementAudit: {
      classification: 'READ_ONLY_ROUTE_AND_DOC_AUDIT',
      finding:
        'Sports Center exposes settlement status by linking to existing Performance and foundation evidence. Settlement logic and row movement were not modified in this phase.',
      mutationApplied: false,
      logicChanged: false,
    },
  }
}

export function getSportsCenterSport(key: string): SportsCenterSport | null {
  return SPORTS_CENTER_SPORTS.find((sport) => sport.key === key.toLowerCase() as SportsCenterSportKey) ?? null
}

export function getSportsCenterSportKeys() {
  return SPORTS_CENTER_SPORTS.map((sport) => sport.key)
}
