export const MLB_OPERATING_DAY_WRITE_SCHEDULER_CRON = '7-57/10 * * * *'
export const MLB_OPERATING_DAY_HEARTBEAT_CRON = '3,33 * * * *'
export const MLB_OPERATING_DAY_WRITE_SCHEDULER_INTERVAL_MINUTES = 10
export const MLB_OPERATING_DAY_SCHEDULER_GRACE_MINUTES = 10
