-- Strictly prior-start rolling features for the 2025 pitcher prop research dataset.

create materialized view public.mlb_pitcher_prop_backtest_2025_v1_enriched as
with all_starts as (
  select
    p.id as historical_appearance_id,
    p.pitcher_source_id,
    g.game_date,
    p.strikeouts,
    p.outs,
    p.walks,
    p.hits,
    p.runs,
    p.pitch_count,
    p.batters_faced
  from public.historical_baseball_pitcher_appearances p
  join public.historical_baseball_games g
    on g.canonical_game_id = p.canonical_game_id
  where g.season = '2025'
    and p.starter = true
), rolling as (
  select
    a.historical_appearance_id,
    a.pitcher_source_id,
    a.game_date,
    a.strikeouts,
    a.outs,
    a.walks,
    a.hits,
    a.runs,
    a.pitch_count,
    a.batters_faced,
    count(*) over wprior as prior_start_count,
    avg(a.strikeouts) over w3 as prior_k_l3,
    avg(a.strikeouts) over w5 as prior_k_l5,
    avg(a.strikeouts) over w10 as prior_k_l10,
    avg(a.strikeouts) over wprior as prior_k_all,
    avg(a.outs) over w3 as prior_outs_l3,
    avg(a.outs) over w5 as prior_outs_l5,
    avg(a.outs) over w10 as prior_outs_l10,
    avg(a.outs) over wprior as prior_outs_all,
    avg(a.walks) over w3 as prior_bb_l3,
    avg(a.walks) over w5 as prior_bb_l5,
    avg(a.walks) over w10 as prior_bb_l10,
    avg(a.walks) over wprior as prior_bb_all,
    avg(a.hits) over w3 as prior_hits_l3,
    avg(a.hits) over w5 as prior_hits_l5,
    avg(a.hits) over w10 as prior_hits_l10,
    avg(a.hits) over wprior as prior_hits_all,
    avg(a.runs) over w3 as prior_runs_l3,
    avg(a.runs) over w5 as prior_runs_l5,
    avg(a.runs) over w10 as prior_runs_l10,
    avg(a.runs) over wprior as prior_runs_all,
    avg(a.pitch_count) over w3 as prior_pitch_count_l3,
    avg(a.pitch_count) over w5 as prior_pitch_count_l5,
    avg(a.pitch_count) over w10 as prior_pitch_count_l10,
    avg(a.pitch_count) over wprior as prior_pitch_count_all,
    avg(a.batters_faced) over w3 as prior_bf_l3,
    avg(a.batters_faced) over w5 as prior_bf_l5,
    avg(a.batters_faced) over w10 as prior_bf_l10,
    avg(a.batters_faced) over wprior as prior_bf_all
  from all_starts a
  window
    w3 as (partition by a.pitcher_source_id order by a.game_date, a.historical_appearance_id rows between 3 preceding and 1 preceding),
    w5 as (partition by a.pitcher_source_id order by a.game_date, a.historical_appearance_id rows between 5 preceding and 1 preceding),
    w10 as (partition by a.pitcher_source_id order by a.game_date, a.historical_appearance_id rows between 10 preceding and 1 preceding),
    wprior as (partition by a.pitcher_source_id order by a.game_date, a.historical_appearance_id rows between unbounded preceding and 1 preceding)
)
select
  b.historical_appearance_id,
  b.canonical_game_id,
  b.target_game_pk,
  b.game_date,
  b.fixed_split,
  b.pitcher_source_id,
  b.mlbam_pitcher_id,
  b.pitcher_name,
  b.mapping_method,
  b.team_side,
  b.pitcher_team_abbr,
  b.opponent_team_abbr,
  b.pitcher_team_id,
  b.opponent_team_id,
  b.pitcher_feature_id,
  b.opponent_team_feature_id,
  b.matchup_feature_id,
  b.feature_version,
  b.pitcher_as_of_date,
  b.opponent_as_of_date,
  b.matchup_as_of_date,
  b.target_strikeouts,
  b.target_outs,
  b.target_walks,
  b.target_hits_allowed,
  b.target_runs_allowed,
  b.target_pitch_count,
  b.target_batters_faced,
  b.pitcher_k_rate,
  b.pitcher_bb_rate,
  b.pitcher_k_minus_bb_rate,
  b.pitcher_whiff_rate,
  b.pitcher_csw_rate,
  b.pitcher_strike_rate,
  b.pitcher_swing_rate,
  b.pitcher_avg_release_speed,
  b.pitcher_velocity_l1,
  b.pitcher_velocity_l3,
  b.pitcher_velocity_l5,
  b.pitcher_velocity_delta,
  b.previous_pitch_count,
  b.days_rest,
  b.pitcher_prior_appearances,
  b.pitcher_prior_pitches,
  b.pitcher_prior_plate_appearances,
  b.pitcher_first_inning_k_rate,
  b.pitcher_first_inning_bb_rate,
  b.pitcher_first_inning_pitch_count_avg,
  b.opponent_recent_k_rate,
  b.opponent_recent_bb_rate,
  b.opponent_recent_runs_per_game,
  b.opponent_recent_iso,
  b.opponent_prior_games,
  b.opponent_prior_pitches,
  b.opponent_prior_plate_appearances,
  b.opponent_lineup_proxy_batter_count,
  b.pitch_mix,
  b.pitch_mix_change,
  b.pitcher_handedness_context,
  b.first_inning_performance,
  b.pitcher_sample_sizes,
  b.pitcher_source_window,
  b.opponent_handedness_context,
  b.opponent_lineup_proxy,
  b.opponent_sample_sizes,
  b.opponent_source_window,
  b.matchup_pitcher_batter_mix,
  b.matchup_handedness_context,
  b.matchup_lineup_context,
  b.matchup_sample_sizes,
  b.matchup_source_window,
  r.prior_start_count,
  r.prior_k_l3,
  r.prior_k_l5,
  r.prior_k_l10,
  r.prior_k_all,
  r.prior_outs_l3,
  r.prior_outs_l5,
  r.prior_outs_l10,
  r.prior_outs_all,
  r.prior_bb_l3,
  r.prior_bb_l5,
  r.prior_bb_l10,
  r.prior_bb_all,
  r.prior_hits_l3,
  r.prior_hits_l5,
  r.prior_hits_l10,
  r.prior_hits_all,
  r.prior_runs_l3,
  r.prior_runs_l5,
  r.prior_runs_l10,
  r.prior_runs_all,
  r.prior_pitch_count_l3,
  r.prior_pitch_count_l5,
  r.prior_pitch_count_l10,
  r.prior_pitch_count_all,
  r.prior_bf_l3,
  r.prior_bf_l5,
  r.prior_bf_l10,
  r.prior_bf_all
from public.mlb_pitcher_prop_backtest_2025_v1 b
join rolling r using (historical_appearance_id);

create unique index mlb_pitcher_prop_backtest_2025_v1_enriched_appearance_uidx
  on public.mlb_pitcher_prop_backtest_2025_v1_enriched (historical_appearance_id);
create index mlb_pitcher_prop_backtest_2025_v1_enriched_pitcher_date_idx
  on public.mlb_pitcher_prop_backtest_2025_v1_enriched (mlbam_pitcher_id, game_date);
create index mlb_pitcher_prop_backtest_2025_v1_enriched_split_date_idx
  on public.mlb_pitcher_prop_backtest_2025_v1_enriched (fixed_split, game_date);

revoke all on public.mlb_pitcher_prop_backtest_2025_v1_enriched from public, anon, authenticated;
grant select on public.mlb_pitcher_prop_backtest_2025_v1_enriched to service_role;
