import fs from 'node:fs';import {execFileSync} from 'node:child_process';import crypto from 'node:crypto';
const baseline='12de8d43ffac19b908732305d349da8d6944a77d',hash=x=>crypto.createHash('sha256').update(x).digest('hex'),paths=execFileSync('git',['ls-tree','-r','--name-only',baseline,'artifacts/research'],{encoding:'utf8'}).trim().split(/\r?\n/),inventory=[],records=[];
const read=path=>JSON.parse(execFileSync('git',['show',`${baseline}:${path}`],{encoding:'utf8',maxBuffer:30*1024*1024}));
function add(market,m,path,family,cohort){const n=m.n??m.nonpush??((m.wins??0)+(m.losses??0)),month=m.monthly??m.months??{},months=m.months_with_selections??m.selected_months??(m.monthly||m.months?Object.values(month).filter(x=>x.n>0).length:null);records.push({market,architecture:family,cohort,artifact:path,accuracy:m.accuracy??null,n,coverage:m.coverage??m.coverage_vs_oof_all??m.coverage_vs_oof??m.coverage_vs_oof_nonpush??null,coverage_definition:m.coverage_definition??(m.coverage!==undefined?'selected/eligible':m.coverage_vs_oof_all!==undefined?'selected incl pushes/all OOF':m.coverage_vs_oof_nonpush!==undefined?'nonpush selected/nonpush OOF':'original artifact denominator; unknown if null'),worst_month:m.worst_month_accuracy??null,months,minimum_month_n:m.min_month_n??(Object.values(month).filter(x=>x.n>0).length?Math.min(...Object.values(month).filter(x=>x.n>0).map(x=>x.n)):null),pushes:m.pushes??0,original_gate:m.development_gate_pass??m.target_met_75_plus??null});}
for(const path of paths){const file=path.split('/').at(-1);let classification='INVENTORY_ONLY_SUPPORT_OR_OUT_OF_SCOPE';if(/external|forward|2026_proxy|2026_diagnostic|2026_decisions|runtime|official_pick/.test(file))classification='EXCLUDED_EXTERNAL_FORWARD_OR_OPERATIONAL';else if(file.endsWith('.gz'))classification='COMPRESSED_EVIDENCE_REFERENCED_BY_SUMMARY';else if(file.endsWith('.json')){
 let d;const revisit=file.match(/^mlb_(f[1357]_(?:ml|3way|nrfi)|totals)_revisit_v1_result\.json$/),first=file.match(/^mlb_f([1357])_(ml|3way|nrfi|totals)_market_v1_frozen_candidate\.json$/),period=/^mlb_(period_(poisson|davidson|qda|empirical_convolution|bayesian_mixture)_v1_result|new_families_v1_(hierarchical|kalman|archetype|isotonic)|multiperiod_bilinear_v1|honest_regime_tree_v1)\.json$/.test(file);
 if(revisit){d=read(path);classification='CLOSED_HISTORICAL_SELECTED_CANDIDATE';add(revisit[1].toUpperCase(),d.selected_candidate,path,d.selected_candidate.architecture,'historical rolling OOF through <=2026-09-18; no external selection');}
 else if(first){d=read(path);classification='CLOSED_2025_DEVELOPMENT_ONLY';add(`F${first[1]}_${first[2].toUpperCase()}`,d.development_2025,path,'first-pass frozen composite/reference','2025 development only; not comparable to unified OOF');}
 else if(period){d=read(path);classification='CLOSED_FROZEN_OUTCOME_ONLY_FAMILY';for(const[p,v]of Object.entries(d.periods))for(const[market,m]of Object.entries(v.markets))add(`F${p}_${market}`,m,path,d.architecture??file,'historical rolling/prequential development');}
 else if(file==='mlb_f7_stability_block_v1.json'){d=read(path);classification='F7_FROZEN_READ_ONLY';for(const[k,v]of Object.entries(d.rules))add('F7_ML',v.metrics,path,k,'historical common-availability rolling development');}
 else if(file==='mlb_f5_opponent_count_v1.json'){d=read(path);classification='CLOSED_FROZEN_OUTCOME_ONLY_FAMILY';add('F5_ML',d.metrics,path,d.architecture,'historical monthly expanding fits');}
 else if(['mlb_f1_nrfi_factorized_v1_result.json','mlb_nrfi_analog_v1_result.json','mlb_nrfi_boosting_v1.json'].includes(file)){d=read(path);classification='CLOSED_NRFI_ARCHITECTURE';add('F1_NRFI',d.market??{...d,n:d.wins+d.losses},path,d.architecture??file,'historical rolling development; starter caveat on older sources');}
 else if(file==='mlb_nrfi_market_v1_frozen_candidate.json'){d=read(path);classification='CLOSED_2025_DEVELOPMENT_ONLY';add('F1_NRFI',d.development_2025,path,d.model_candidate??d.model_version,'2025 development only');}
 else if(/^mlb_f[37]_totals_reference_v1_frozen_candidate.json$/.test(file)){d=read(path);classification='CLOSED_REFERENCE_LINE_NOT_REAL_MARKET';add(file.includes('f3_')?'F3_TOTALS':'F7_TOTALS',d.development_2025,path,'fixed reference-line projection','2025 diagnostic reference line, not executable market');}
 else if(/frozen_candidate|development_freeze/.test(file)){d=read(path);classification='CLOSED_OTHER_MARKET_DEVELOPMENT_NOT_RANKED';}
 if(d)inventory.push({path,classification,canonical_json_sha256:hash(JSON.stringify(d))});else inventory.push({path,classification});continue;
 }inventory.push({path,classification});}
add('TOTALS',{accuracy:265/479,n:479,coverage:.2538,coverage_definition:'selected/nonpush rolling OOF, rounded from archived doc',worst_month_accuracy:.5263},'docs/research/MLB_MARKET_MODEL_TRACKER.md:840','totals_v37_xyear_under_catboost_v1','2025 chronological development; coverage/worst-month reported rounded; month count unreported');
const marketNames=[...new Set(records.map(x=>x.market))].sort(),latest={F1_ML:'honest regime tree',F3_ML:'honest regime tree',F5_ML:'opponent-adjusted NB count',F7_ML:'consensus/conformal/month-bootstrap; frozen',F1_3WAY:'honest regime tree',F3_3WAY:'honest regime tree',F5_3WAY:'honest regime tree',F7_3WAY:'honest regime tree; F7 frozen',F1_NRFI:'joint NRFI boosting',TOTALS:'CatBoost regression/classification'};
const ranked=xs=>[...xs].filter(x=>x.accuracy!==null).sort((a,b)=>b.accuracy-a.accuracy||b.n-a.n),comparison=marketNames.map(market=>{const rs=records.filter(x=>x.market===market),best=ranked(rs)[0]??null,supported=ranked(rs.filter(x=>x.n>=60))[0]??null;return{market,best_observed_closed:best,best_with_n_at_least_60:supported,latest_family:latest[market]??'reference-line study',stability_status:supported&&supported.worst_month>=.65&&supported.months>=5?'MONTHLY_FLOOR_ONLY_MET':'FAIL_OR_NOT_ESTABLISHED',data_blocker:market.startsWith('F7')?'F7_FROZEN_PENDING_NEW_INFORMATION':market.endsWith('_TOTALS')?'EXACT_HISTORICAL_LINE_COVERAGE':market==='TOTALS'?'ARCHIVED_LINEAGE_MIX_REQUIRES_SEPARATE_ADMISSION':market==='F1_NRFI'?'NO_BLOCKER_FOR_OUTCOME_ONLY; older starter features excluded':'NO_BLOCKER_FOR_CERTIFIED_PRIOR_OUTCOMES; legacy wider feature sets not re-admitted',reason_for_fail:best?`${best.n<60?'sample; ':''}${best.accuracy<.75?'accuracy; ':''}${best.worst_month===null||best.worst_month<.65?'monthly stability; ':''}${best.months<5?'months; ':''}closed historical evidence only`:'no qualifying model',closed_records:rs.length};});
const additional=[['F3_SPREAD','No adequate exact historical lines'],['F5_SPREAD','PR186 fixed sample:2/2,coverage2/22=9.09%,one selected month; insufficient exact-line corpus'],['F7_SPREAD','F7 frozen; no adequate exact historical lines'],['PERIOD_ALTERNATE_SPREADS','No exact historical lines; margins are not a sportsbook-line backtest'],['F3_TOTALS','Fixed reference2.5 is not historical exact line'],['F7_TOTALS','Fixed reference6.5 is not historical exact line; F7 frozen'],['ALTERNATE_PERIOD_TOTALS','No adequate exact historical lines'],['TEAM_TOTALS_AND_ALTERNATES','No adequate exact historical lines; team-run threshold classifier diagnostic only'],['GAME_ALTERNATE_SPREADS_TOTALS','No adequate exact historical lines'],['GAME_3WAY','Settlement semantics not certified'],['LINEUP_DEPENDENT_MARKETS','BLOCKED_LINEUP_FEATURE_LINEAGE'],['ALREADY_QUALIFIED_OR_OPERATIONAL_PROPS','Outside below-target research continuation; no operational work'],['BATTER_RUNS_AND_OTHER_PARTICIPATION_PROPS','Do not reopen from external outcomes; lineup/participation and exact-line admission required']].map(([market,data_blocker])=>({market,best_observed_closed:null,best_with_n_at_least_60:null,latest_family:'See preserved closeouts',stability_status:'BLOCKED_OR_EXCLUDED',data_blocker,reason_for_fail:data_blocker}));comparison.push(...additional.filter(r=>!marketNames.includes(r.market)));
const spread=comparison.find(r=>r.market==='F5_SPREAD');
spread.best_observed_closed={accuracy:1,n:2,coverage:2/22,worst_month:1,months:1,artifact:'https://github.com/jlebronmarty-netizen/pick-analyzer/blob/7ef615585f046f6ab885961dee927e5347c3593d/artifacts/research/mlb_f5_spread_transfer_diagnostic_v1.json',cohort:'2025 bought exact-line diagnostic only'};
const output={baseline,main_at_review:'8df2a5ba3d81aa64334fd0dd73361c23c025aa8c',research_only:true,external_opened:false,odds_api_credits:0,scope:'Complete baseline artifact inventory; closed in-scope frozen candidate summaries normalized. External/forward/operational files inventoried only, no outcome arrays opened or used for prioritization. Historical candidate grids are not rescanned; preserve only selected/frozen formulas. Null is unreported, not zero.',inventory,records,comparison};
fs.writeFileSync('artifacts/research/mlb_closed_market_inventory_v1.json',JSON.stringify(output,null,2)+'\n');
const pct=x=>x===null||x===undefined?'NR':(100*x).toFixed(2)+'%',f=x=>x?`${pct(x.accuracy)} (n=${x.n})`:'NR';let doc='# Closed market comparison before new architecture selection\n\nResearch-only. Baseline12de8d43; live main8df2a5ba. Read-only evidence aggregation, no old artifact or tracker changes.\n\n';doc+='Raw maxima and n>=60 references are separated. Cohorts differ; these are not controlled head-to-head results. NR means unavailable in the artifact. Coverage denominators are preserved in JSON, not invented. No external/forward outcome artifact or within-artifact candidate grid was used for ranking.\n\n| Market | Best closed historical accuracy/n | Coverage | Worst month | Best n>=60 reference | Stability status | Last family | Blocker / failure |\n|---|---|---|---|---|---|---|---|\n';for(const r of comparison)doc+=`|${r.market}|${f(r.best_observed_closed)}|${pct(r.best_observed_closed?.coverage)}|${pct(r.best_observed_closed?.worst_month)}|${f(r.best_with_n_at_least_60)}|${r.stability_status}|${r.latest_family}|${r.data_blocker}; ${r.reason_for_fail}|\n`;doc+='\nFull inventory, every normalized candidate, exact artifact paths, cohort labels and reported metric denominators: `artifacts/research/mlb_closed_market_inventory_v1.json`. Recently closed families (including F7 selectors and F5 opponent-count) stay frozen. A market does not inherit a passed gate from a different season/cohort or tiny raw maximum.\n';fs.writeFileSync('docs/research/MLB_CLOSED_MARKET_COMPARISON_V1.md',doc);console.log(JSON.stringify({inventory:inventory.length,records:records.length,comparison:comparison.filter(r=>!r.data_blocker.includes('Outside')).map(r=>({market:r.market,best:f(r.best_observed_closed),supported:f(r.best_with_n_at_least_60),supported_worst:pct(r.best_with_n_at_least_60?.worst_month),blocker:r.data_blocker}))},null,2));
