import fs from 'node:fs';
import zlib from 'node:zlib';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const load=n=>JSON.parse(zlib.gunzipSync(fs.readFileSync(`artifacts/research/mlb_lineup_integrity_v1.${n}.json.gz`)));
export function audit(projected,raw,schedules){
 const games=[...new Map(projected.rows.map(r=>[r[0],{game_pk:r[0],game_date:r[1]}])).values()];
 const chosen=[...games.slice(0,2).map(x=>({...x,stratum:'early'})),...games.filter(x=>x.game_date>='2025-06-15').slice(0,2).map(x=>({...x,stratum:'mid'})),...games.slice(-2).map(x=>({...x,stratum:'late'}))];
 for(const [i,s] of [[0,'extreme_pa'],[6,'extreme_hr']]){const r=[...projected.rows].sort((a,b)=>b[4][i]-a[4][i]||a[0]-b[0]||a[3]-b[3])[0];chosen.push({game_pk:r[0],game_date:r[1],stratum:s,batter:r[3],value:r[4][i]});}
 const ids=new Set(chosen.map(x=>x.game_pk)),schedule=new Map(schedules.map(x=>[x.game_pk,x])),rg=new Map(raw.rows.map(r=>[`${r[0]}:${r[2]}:${r[3]}`,r]));
 const records=projected.rows.filter(r=>ids.has(r[0])).map(r=>{
  const s=schedule.get(r[0]);assert(s,'MISSING_SCHEDULE');const scheduled=Date.parse(s.scheduled_at),inputs=r[9].map(id=>{const v=rg.get(`${id}:${r[2]}:${r[3]}`);assert(v,'MISSING_RAW');return {game_pk:id,event_date:v[1],source_row_timestamp_min:v[14],source_row_timestamp_max:v[15],raw_digest:v[6],timestamp_semantics:'stored ingestion bounds, not upstream publication'};});
  const earliest=Math.min(...inputs.map(v=>Date.parse(v.source_row_timestamp_min))),latest=Math.max(...inputs.map(v=>Date.parse(v.source_row_timestamp_max)));
  return {game_pk:r[0],game_date:r[1],team:r[2],batter:r[3],strata:chosen.filter(x=>x.game_pk===r[0]).map(x=>x.stratum),scheduled_at:new Date(scheduled).toISOString(),schedule_captured_at:s.fetched_at,schedule_source:s.source,scheduled_at_pregame_verified:false,actual_first_pitch:null,cutoff:new Date(scheduled-3600000).toISOString(),cutoff_t30:new Date(scheduled-1800000).toISOString(),cutoff_semantics:'T-60/T-30 diagnostic from retrospective final schedule; not a certified original cutoff',builder_calculation_cutoff_date_exclusive:r[1],source_row_timestamp:new Date(latest).toISOString(),earliest_source_row_timestamp:new Date(earliest).toISOString(),source_version:'baseball-savant-statcast-2025-original',builder_version_sha:null,reconstruction_sha:'a37fe5a742dddafd96d002de0038b705ad16aee9',upstream_builder_migration:'20260915203807',feature_version:null,source_inputs:inputs,all_stored_inputs_ingested_after_game:earliest>scheduled,gate_A:false,gate_B:false,gate_C:false,pregame_lineage:'FAIL',reasons:['NO_VERIFIED_PREGAME_SNAPSHOT','NO_IMMUTABLE_UPSTREAM_PUBLICATION_HISTORY','ORIGINAL_BUILDER_AND_FEATURE_VERSION_MISSING','SCHEDULE_AS_PUBLISHED_UNVERIFIED']};
 });
 return {status:'BLOCKED_LINEUP_FEATURE_LINEAGE',research_only:true,external_opened:false,odds_api_credits:0,sample_design:chosen,uncovered_strata:[{stratum:'late_lineup_changes',reason:'No timestamped2025 lineup revision sequence; observed substitutions cannot identify late pregame changes.'},{stratum:'prediction_importance',reason:'Extreme PA/HR are deterministic stress proxies; no certified lineup-model attribution is asserted.'}],sample_games:ids.size,sample_records:records.length,passed:0,failed:records.length,expanded_to_full_2025:false,expanded_to_2026:false,records};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const out=audit(load('projected'),load('raw'),JSON.parse(fs.readFileSync('artifacts/research/mlb_lineup_lineage_sample_v1.schedule.json')));fs.writeFileSync('artifacts/research/mlb_lineup_lineage_sample_v1.result.json',JSON.stringify(out,null,2)+'\n');console.log({games:out.sample_games,records:out.sample_records,passed:out.passed,failed:out.failed});}
