import fs from 'node:fs';import zlib from 'node:zlib';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {metrics} from './evaluate_mlb_new_families_v1.mjs';
export const contract=JSON.parse(fs.readFileSync(new URL('../../contracts/MLB_HONEST_REGIME_TREE_V1.json',import.meta.url)));const classes=['HOME','AWAY','DRAW'],hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const counts=rows=>classes.map(c=>rows.filter(r=>r.truth===c).length),impurity=rows=>{const n=rows.length;return n? n-counts(rows).reduce((s,c)=>s+c*c/n,0):0;};
export function structure(rows,depth=0){const leaf={leaf:true,calibration:[0,0,0],calibration_n:0,structure_n:rows.length};if(depth>=3||rows.length<80)return leaf;const before=impurity(rows);let best=null;
 for(let feature=1;feature<=8;feature++){const values=rows.map(r=>r.features[feature]).sort((a,b)=>a-b);for(const fraction of [1/3,2/3]){const threshold=values[Math.floor((values.length-1)*fraction)],left=rows.filter(r=>r.features[feature]<=threshold),right=rows.filter(r=>r.features[feature]>threshold);if(Math.min(left.length,right.length)<40)continue;const gain=before-impurity(left)-impurity(right);if(gain>0&&(!best||gain>best.gain))best={feature,threshold,left,right,gain};}}
 return best?{leaf:false,feature:best.feature,threshold:best.threshold,left:structure(best.left,depth+1),right:structure(best.right,depth+1)}:leaf;
}
export function leafFor(tree,row){let node=tree;while(!node.leaf)node=row.features[node.feature]<=node.threshold?node.left:node.right;return node;}
export function fit(history){const split=history.filter(r=>r.game_pk%2===0),cal=history.filter(r=>r.game_pk%2!==0);if(history.length<500||Math.min(split.length,cal.length)<200)return null;const tree=structure(split);for(const r of cal){const n=leafFor(tree,r);n.calibration_n++;n.calibration[classes.indexOf(r.truth)]++;}const base=counts(history).map(v=>(v+1)/(history.length+3));return {tree,base,structure_n:split.length,calibration_n:cal.length};}
export function evaluate(input){const rows=[...input].sort((a,b)=>a.game_date.localeCompare(b.game_date)||a.game_pk-b.game_pk),ids=new Set();for(const r of rows){assert(/^(2025|2026)-/.test(r.game_date)&&r.game_date<='2026-09-18','DATE');assert(Number.isSafeInteger(r.game_pk)&&!ids.has(r.game_pk),'IDENTITY');ids.add(r.game_pk);assert(classes.includes(r.truth)&&r.features.length===37&&r.features.every(Number.isFinite),'FEATURES');}let season=null,month=null,history=[],model=null;const predictions=[],fits=[];let excluded=0;
 for(let i=0;i<rows.length;){let j=i+1;while(j<rows.length&&rows[j].game_date===rows[i].game_date)j++;const year=rows[i].game_date.slice(0,4),m=rows[i].game_date.slice(0,7);if(year!==season){season=year;month=null;history=[];model=null;}if(m!==month){month=m;model=fit(history);if(model)fits.push({fit_date:rows[i].game_date,max_training_date:history.at(-1).game_date,structure_n:model.structure_n,calibration_n:model.calibration_n,tree:model.tree});}
  for(const r of rows.slice(i,j)){if(!model){excluded++;continue;}const leaf=leafFor(model.tree,r);if(leaf.calibration_n<30){excluded++;continue;}const p=leaf.calibration.map((v,k)=>(v+10*model.base[k])/(leaf.calibration_n+10)),ml=p[0]/(p[0]+p[1]),best=p.indexOf(Math.max(...p));predictions.push({game_pk:r.game_pk,game_date:r.game_date,probabilities:Object.fromEntries(classes.map((c,k)=>[c,p[k]])),truth:r.truth,ml_side:ml>=.75?'HOME':ml<=.25?'AWAY':null,threeway_side:p[best]>=.75?classes[best]:null,calibration_leaf_n:leaf.calibration_n,baseline_ml:r.baseline_ml,baseline_threeway:r.baseline_threeway});}history.push(...rows.slice(i,j));i=j;
 }return {source_contexts:rows.length,eligible:predictions.length,excluded,markets:{ML:metrics(predictions,'ML'),'3WAY':metrics(predictions,'3WAY')},fits,predictions};}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const bytes=fs.readFileSync('artifacts/research/mlb_multiperiod_bilinear_v1.json.gz'),source=JSON.parse(zlib.gunzipSync(bytes)),full={architecture:contract.architecture,contract_sha256:hash(JSON.stringify(contract)),feature_artifact_sha256:hash(bytes),research_only:true,external_opened:false,odds_api_credits:0,periods:Object.fromEntries(contract.periods.map(p=>[p,evaluate(source.periods[p].predictions)]))},text=JSON.stringify(full);fs.writeFileSync('artifacts/research/mlb_honest_regime_tree_v1.json.gz',zlib.gzipSync(text));for(const v of Object.values(full.periods)){delete v.predictions;delete v.fits;}full.full_result_sha256=hash(text);fs.writeFileSync('artifacts/research/mlb_honest_regime_tree_v1.json',JSON.stringify(full,null,2)+'\n');console.log(JSON.stringify(full,null,2));}
