import fs from 'node:fs';import zlib from 'node:zlib';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {metrics} from './evaluate_mlb_new_families_v1.mjs';
export const contract=JSON.parse(fs.readFileSync(new URL('../../contracts/MLB_MULTIPERIOD_BILINEAR_V1.json',import.meta.url)));const ps=[1,3,5,7],cls=['HOME','AWAY','DRAW'],hash=x=>crypto.createHash('sha256').update(x).digest('hex');
export function join(source){const maps=ps.map(p=>{const m=new Map();for(const r of source[p]){assert(r.length===11&&[2025,2026].includes(r[0])&&r[2].startsWith(String(r[0]))&&r[2]<='2026-09-18','DATE');assert(r[7]<r[2]&&r[9]===true&&r[10]==='HISTORICAL_SEEN_DEVELOPMENT'&&new RegExp('F'+p+'(?:_|$)').test(r[8]),'LINEAGE');for(const k of [1,3,4])assert(Number.isSafeInteger(r[k])&&r[k]>=(k===1?1:0),'IDENTITY');const k=r[0]+':'+r[1];assert(!m.has(k),'DUPLICATE');m.set(k,r);}return m;});
 const result=[];for(const[k,r]of maps[0]){if(!maps.every(m=>m.has(k)))continue;const rs=maps.map(m=>m.get(k));assert(rs.every(q=>q[2]===r[2]&&q[5]===r[5]&&q[6]===r[6]),'IDENTITY_CONFLICT');assert(r[5]&&r[6]&&r[5]!==r[6],'TEAM');assert(rs.every((q,i)=>!i||q[3]>=rs[i-1][3]&&q[4]>=rs[i-1][4]),'NONMONOTONIC');result.push({year:r[0],id:r[1],date:r[2],home:r[5],away:r[6],home_runs:rs.map(q=>q[3]),away_runs:rs.map(q=>q[4]),hs:rs.map((q,i)=>q[3]-(i?rs[i-1][3]:0)),as:rs.map((q,i)=>q[4]-(i?rs[i-1][4]:0))});}return result.sort((a,b)=>a.date.localeCompare(b.date)||a.id-b.id);}
export function featureMap(x){assert.equal(x.length,8);const v=[1,...x];for(let i=0;i<8;i++)for(let j=i+1;j<8;j++)v.push(x[i]*x[j]);return v;}
const softmax=(w,x)=>{const z=w.map(r=>r.reduce((s,v,i)=>s+v*x[i],0)),max=Math.max(...z),e=z.map(v=>Math.exp(v-max)),n=e.reduce((a,b)=>a+b,0);return e.map(v=>v/n);};
export function evaluate(source){const rows=join(source),states=new Map(),predictions=ps.map(()=>[]);let excludedHistory=0,excludedTraining=0;
 for(let i=0;i<rows.length;){let j=i+1;while(j<rows.length&&rows[j].date===rows[i].date)j++;const year=rows[i].year;if(!states.has(year))states.set(year,{n:0,trained:0,segment:[0,0,0,0],counts:ps.map(()=>[0,0,0]),teams:new Map(),weights:ps.map(()=>cls.map(()=>Array(37).fill(0)))});const s=states.get(year),pending=[];
  for(const r of rows.slice(i,j)){const h=s.teams.get(r.home)??[],a=s.teams.get(r.away)??[];if(s.n<300||Math.min(h.length,a.length)<20){excludedHistory++;continue;}const rate=(t,side,k)=>Math.log1p((t.reduce((n,v)=>n+v[side][k],0)+10*s.segment[k]/(2*s.n))/(t.length+10)),x=featureMap([...Array.from({length:4},(_,k)=>rate(h,0,k)-rate(a,0,k)),...Array.from({length:4},(_,k)=>rate(a,1,k)-rate(h,1,k))]),probs=s.weights.map(w=>softmax(w,x)),truth=r.home_runs.map((v,k)=>v>r.away_runs[k]?0:v<r.away_runs[k]?1:2);pending.push({x,probs,truth});
   if(s.trained<300){excludedTraining++;continue;}for(let k=0;k<4;k++){const p=probs[k],base=s.counts[k].map(v=>(v+1)/(s.n+3)),ml=p[0]/(p[0]+p[1]),best=p.indexOf(Math.max(...p));predictions[k].push({game_pk:r.id,game_date:r.date,features:x,prior_training_games:s.trained,probabilities:Object.fromEntries(cls.map((c,i)=>[c,p[i]])),ml_side:ml>=.75?'HOME':ml<=.25?'AWAY':null,threeway_side:p[best]>=.75?cls[best]:null,truth:cls[truth[k]],baseline_probabilities:base,baseline_ml:base[0]>=base[1]?'HOME':'AWAY',baseline_threeway:cls[base.indexOf(Math.max(...base))]});}}
  if(pending.length){for(let k=0;k<4;k++)for(let c=0;c<3;c++)for(let f=0;f<37;f++){const g=pending.reduce((n,v)=>n+(v.probs[k][c]-Number(v.truth[k]===c))*v.x[f],0)/pending.length+(f?.01*s.weights[k][c][f]:0);s.weights[k][c][f]-=.1*Math.max(-1,Math.min(1,g));}s.trained+=pending.length;}
  for(const r of rows.slice(i,j)){s.n++;r.hs.forEach((v,k)=>s.segment[k]+=v+r.as[k]);for(let k=0;k<4;k++)s.counts[k][r.home_runs[k]>r.away_runs[k]?0:r.home_runs[k]<r.away_runs[k]?1:2]++;for(const[id,scored,allowed]of [[r.home,r.hs,r.as],[r.away,r.as,r.hs]]){const t=s.teams.get(id)??[];t.push([scored,allowed]);if(t.length>30)t.shift();s.teams.set(id,t);}}i=j;}
 return {joined_games:rows.length,joined_sha256:hash(JSON.stringify(rows)),excluded_history:excludedHistory,excluded_training:excludedTraining,periods:Object.fromEntries(ps.map((p,k)=>[p,{eligible:predictions[k].length,markets:{ML:metrics(predictions[k],'ML'),'3WAY':metrics(predictions[k],'3WAY')},predictions:predictions[k]}]))};}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const source=JSON.parse(fs.readFileSync(process.argv[2])),prior=JSON.parse(fs.readFileSync('artifacts/research/mlb_period_poisson_v1_result.json'));for(const p of ps)assert.equal(hash(JSON.stringify([...source[p]].sort((a,b)=>a[2].localeCompare(b[2])||a[1]-b[1]))),prior.periods[p].input_sha256,'SOURCE_HASH');const full={architecture:contract.architecture,contract_sha256:hash(JSON.stringify(contract)),research_only:true,external_opened:false,odds_api_credits:0,...evaluate(source)},t=JSON.stringify(full);fs.writeFileSync('artifacts/research/mlb_multiperiod_bilinear_v1.json.gz',zlib.gzipSync(t));for(const v of Object.values(full.periods))delete v.predictions;full.full_result_sha256=hash(t);fs.writeFileSync('artifacts/research/mlb_multiperiod_bilinear_v1.json',JSON.stringify(full,null,2)+'\n');console.log(JSON.stringify(full,null,2));}
