import fs from 'node:fs';import zlib from 'node:zlib';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
export const contract=JSON.parse(fs.readFileSync(new URL('../../contracts/MLB_PERIOD_BAYESIAN_EXPERT_MIXTURE_V1.json',import.meta.url)));
const hash=x=>crypto.createHash('sha256').update(x).digest('hex');const cls=['HOME','AWAY','DRAW'];
export function evaluate(experts){
 assert.equal(experts.length,3);const maps=experts.map(rows=>{const m=new Map();for(const r of rows){assert(r.game_date<='2026-09-18'&&/^(2025|2026)-/.test(r.game_date),'DATE');assert(Number.isSafeInteger(r.game_pk),'IDENTITY');assert(cls.includes(r.truth),'TRUTH');assert(cls.every(c=>Number.isFinite(r.probabilities[c])&&r.probabilities[c]>=0),'PROBABILITY');assert(Math.abs(cls.reduce((n,c)=>n+r.probabilities[c],0)-1)<1e-8,'MASS');const k=r.game_date+':'+r.game_pk;assert(!m.has(k),'DUPLICATE');m.set(k,r);}return m;});
 const rows=[...maps[0]].filter(([k])=>maps.every(m=>m.has(k))).map(([k,r])=>({key:k,...r})).sort((a,b)=>a.game_date.localeCompare(b.game_date)||a.game_pk-b.game_pk);const predictions=[];let season=null,logs=[0,0,0],prior=0;
 for(let i=0;i<rows.length;){let j=i+1;while(j<rows.length&&rows[j].game_date===rows[i].game_date)j++;if(season!==rows[i].game_date.slice(0,4)){season=rows[i].game_date.slice(0,4);logs=[0,0,0];prior=0;}const max=Math.max(...logs),ws=logs.map(x=>Math.exp(x-max)),sum=ws.reduce((a,b)=>a+b,0),weights=ws.map(x=>x/sum);
  for(const r of rows.slice(i,j)){const es=maps.map(m=>m.get(r.key));assert(es.every(x=>x.truth===r.truth),'TRUTH_MISMATCH');const p=Object.fromEntries(cls.map(c=>[c,es.reduce((n,e,k)=>n+weights[k]*e.probabilities[c],0)]));const ml=p.HOME+p.AWAY>0?p.HOME/(p.HOME+p.AWAY):null,best=Object.entries(p).sort((a,b)=>b[1]-a[1])[0];predictions.push({game_pk:r.game_pk,game_date:r.game_date,weights,prior_training_games:prior,probabilities:p,ml_home_conditional:ml,ml_side:ml===null?null:ml>=.75?'HOME':ml<=.25?'AWAY':null,threeway_side:best[1]>=.75?best[0]:null,truth:r.truth});}
  for(const r of rows.slice(i,j)){maps.forEach((m,k)=>logs[k]+=Math.log(Math.max(m.get(r.key).probabilities[r.truth],1e-12)));prior++;}i=j;
 }
 const markets={};for(const [market,key] of [['ML','ml_side'],['3WAY','threeway_side']]){const selected=predictions.filter(r=>r[key]!==null),decided=selected.filter(r=>market!=='ML'||r.truth!=='DRAW'),wins=decided.filter(r=>r[key]===r.truth).length,monthly={};for(const r of decided){const k=r.game_date.slice(0,7);monthly[k]??={n:0,wins:0};monthly[k].n++;monthly[k].wins+=Number(r[key]===r.truth);}for(const m of Object.values(monthly))m.accuracy=m.wins/m.n;const accuracy=decided.length?wins/decided.length:null,worst=decided.length?Math.min(...Object.values(monthly).map(m=>m.accuracy)):null;markets[market]={selected:selected.length,wins,losses:decided.length-wins,pushes:selected.length-decided.length,accuracy,coverage:predictions.length?selected.length/predictions.length:null,monthly,worst_month_accuracy:worst,development_gate_pass:accuracy!==null&&accuracy>=.75&&decided.length>=60&&Object.keys(monthly).length>=5&&worst>=.65};}
 return {eligible:predictions.length,expert_eligible:experts.map(x=>x.length),markets,predictions};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const sources=contract.experts.map(e=>{const bytes=fs.readFileSync(`artifacts/research/mlb_period_${e}_v1_result.json.gz`);return {sha256:hash(bytes),data:JSON.parse(zlib.gunzipSync(bytes))};});const periods=Object.fromEntries(contract.periods.map(p=>{const hs=sources.map(s=>s.data.periods[p].input_sha256);assert(hs.every(x=>x===hs[0]),'SOURCE_HASH');return[p,{input_sha256:hs[0],...evaluate(sources.map(s=>s.data.periods[p].predictions))}];}));const full={architecture:contract.architecture,contract_sha256:hash(JSON.stringify(contract)),expert_artifact_sha256:sources.map(s=>s.sha256),research_only:true,external_opened:false,odds_api_credits:0,periods};const text=JSON.stringify(full);fs.writeFileSync('artifacts/research/mlb_period_bayesian_mixture_v1_result.json.gz',zlib.gzipSync(text));for(const p of Object.values(full.periods))delete p.predictions;full.full_result_sha256=hash(text);fs.writeFileSync('artifacts/research/mlb_period_bayesian_mixture_v1_result.json',JSON.stringify(full,null,2)+'\n');console.log(JSON.stringify(full,null,2));}
