import fs from 'node:fs';import zlib from 'node:zlib';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
import {hash,robustness} from './evaluate_mlb_f7_stability_block_v1.mjs';
export const contract=JSON.parse(fs.readFileSync(new URL('../../contracts/MLB_F5_OPPONENT_COUNT_V1.json',import.meta.url)));
export function solve(A,b){const n=b.length,L=Array.from({length:n},()=>Array(n).fill(0));for(let i=0;i<n;i++)for(let j=0;j<=i;j++){let v=A[i][j];for(let k=0;k<j;k++)v-=L[i][k]*L[j][k];if(i===j){assert(v>0&&Number.isFinite(v),'SPD');L[i][j]=Math.sqrt(v);}else L[i][j]=v/L[j][j];}const y=Array(n),x=Array(n);for(let i=0;i<n;i++){let v=b[i];for(let j=0;j<i;j++)v-=L[i][j]*y[j];y[i]=v/L[i][i];}for(let i=n-1;i>=0;i--){let v=y[i];for(let j=i+1;j<n;j++)v-=L[j][i]*x[j];x[i]=v/L[i][i];}return x;}
const mean=z=>Math.exp(Math.max(-5,Math.min(Math.log(50),z)));
export function fit(rows){assert(rows.length>=600,'TRAINING');const teams=[...new Set(rows.flatMap(r=>[r[5],r[6]]))].sort(),N=teams.length,indices=new Map(teams.map((t,i)=>[t,i])),counts=Object.fromEntries(teams.map(t=>[t,0])),observations=[];for(const r of rows){counts[r[5]]++;counts[r[6]]++;observations.push({y:r[3],x:[0,1,2+indices.get(r[5]),2+N+indices.get(r[6])]}, {y:r[4],x:[0,2+indices.get(r[6]),2+N+indices.get(r[5])]});}const d=2+2*N,w=Array(d).fill(0),penalty=Array.from({length:d},(_,i)=>i===0?1e-6:i===1?10:20);w[0]=Math.log((observations.reduce((s,r)=>s+r.y,0)+1)/(observations.length+1));let maxStep=Infinity,iterations=0;
 for(let epoch=0;epoch<50;epoch++){const g=w.map((v,i)=>-penalty[i]*v),H=Array.from({length:d},(_,i)=>Array.from({length:d},(_,j)=>i===j?penalty[i]:0));for(const r of observations){const mu=mean(r.x.reduce((s,i)=>s+w[i],0)),gradient=(r.y-mu)/(1+mu/2),curvature=mu/(1+mu/2);for(const i of r.x){g[i]+=gradient;for(const j of r.x)H[i][j]+=curvature;}}const step=solve(H,g);maxStep=Math.max(...step.map(Math.abs));for(let i=0;i<d;i++)w[i]+=Math.max(-.5,Math.min(.5,step[i]));iterations++;if(maxStep<1e-8)break;}
 return {teams,counts,weights:w,iterations,max_final_step:maxStep,converged:maxStep<=1e-6,training_games:rows.length,max_training_date:rows.at(-1)[2]};
}
export function nb(mu){assert(mu>0&&Number.isFinite(mu),'MEAN');const p=[(2/(2+mu))**2],q=mu/(2+mu);let mass=p[0];for(let n=1;mass<1-1e-12&&n<10000;n++){p.push(p.at(-1)*(n+1)/n*q);mass+=p.at(-1);}assert(mass>=1-1e-12&&mass<=1+1e-10,'TAIL');return p.map(v=>v/mass);}
export function countProbabilities(home,away){const h=nb(home),a=nb(away);let hw=0,aw=0,draw=0,ch=0,ca=0;for(let i=0;i<Math.max(h.length,a.length);i++){const ph=h[i]??0,pa=a[i]??0;hw+=ph*ca;aw+=pa*ch;draw+=ph*pa;ch+=ph;ca+=pa;}const sum=hw+aw+draw;return {HOME:hw/sum,AWAY:aw/sum,DRAW:draw/sum};}
export function predict(model,home,away){const hi=model.teams.indexOf(home),ai=model.teams.indexOf(away);assert(hi>=0&&ai>=0&&hi!==ai,'TEAM');const N=model.teams.length,w=model.weights,mh=mean(w[0]+w[1]+w[2+hi]+w[2+N+ai]),ma=mean(w[0]+w[2+ai]+w[2+N+hi]);return {home_mean:mh,away_mean:ma,probabilities:countProbabilities(mh,ma)};}
export function evaluate(input){const rows=[...input].sort((a,b)=>a[2].localeCompare(b[2])||a[1]-b[1]),ids=new Set();for(const r of rows){assert(r.length===11&&[2025,2026].includes(r[0])&&r[2].startsWith(String(r[0]))&&r[2]<=contract.max_date,'DATE');assert(Number.isSafeInteger(r[1])&&r[1]>0&&!ids.has(r[1]),'IDENTITY');ids.add(r[1]);assert(r[7]<r[2]&&/F5(?:_|$)/.test(r[8])&&r[9]===true&&r[10]==='HISTORICAL_SEEN_DEVELOPMENT','LINEAGE');assert(r[5]&&r[6]&&r[5]!==r[6]&&[r[3],r[4]].every(x=>Number.isSafeInteger(x)&&x>=0),'OUTCOME');}let year=null,month=null,history=[],model=null,counts=[0,0];const predictions=[],fits=[],exclusions={no_fit:0,not_converged:0,team_history:0};
 for(let i=0;i<rows.length;){let j=i+1;while(j<rows.length&&rows[j][2]===rows[i][2])j++;if(rows[i][0]!==year){year=rows[i][0];month=null;history=[];model=null;counts=[0,0];}const m=rows[i][2].slice(0,7);if(m!==month){month=m;model=history.length>=600?fit(history):null;if(model)fits.push({fit_date:rows[i][2],...model});}for(const r of rows.slice(i,j)){if(!model){exclusions.no_fit++;continue;}if(!model.converged){exclusions.not_converged++;continue;}if((model.counts[r[5]]??0)<20||(model.counts[r[6]]??0)<20){exclusions.team_history++;continue;}const p=predict(model,r[5],r[6]),conditional=p.probabilities.HOME/(p.probabilities.HOME+p.probabilities.AWAY);predictions.push({game_pk:r[1],game_date:r[2],...p,conditional_home:conditional,ml_side:conditional>=.75?'HOME':conditional<=.25?'AWAY':null,truth:r[3]>r[4]?'HOME':r[3]<r[4]?'AWAY':'DRAW',baseline_ml:counts[0]>=counts[1]?'HOME':'AWAY',max_training_date:model.max_training_date});}for(const r of rows.slice(i,j)){if(r[3]>r[4])counts[0]++;if(r[3]<r[4])counts[1]++;}history.push(...rows.slice(i,j));i=j;}
 return {source_rows:rows.length,eligible:predictions.length,exclusions,metrics:robustness(predictions),fits,predictions};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const source=JSON.parse(zlib.gunzipSync(fs.readFileSync('artifacts/research/mlb_new_families_v1_source.json.gz')))[5],prior=JSON.parse(fs.readFileSync('artifacts/research/mlb_period_poisson_v1_result.json')),input_sha256=hash(JSON.stringify([...source].sort((a,b)=>a[2].localeCompare(b[2])||a[1]-b[1])));assert.equal(input_sha256,prior.periods[5].input_sha256,'SOURCE_HASH');const full={architecture:contract.architecture,contract_sha256:hash(JSON.stringify(contract)),input_sha256,research_only:true,external_opened:false,odds_api_credits:0,...evaluate(source)},text=JSON.stringify(full);fs.writeFileSync('artifacts/research/mlb_f5_opponent_count_v1.json.gz',zlib.gzipSync(text));delete full.fits;delete full.predictions;full.full_result_sha256=hash(text);full.status=full.metrics.development_gate_pass?'AWAITING_EXTERNAL_AUTHORIZATION':'FAIL';fs.writeFileSync('artifacts/research/mlb_f5_opponent_count_v1.json',JSON.stringify(full,null,2)+'\n');console.log(JSON.stringify(full,null,2));}
