import fs from 'node:fs';
import zlib from 'node:zlib';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {metrics} from './evaluate_mlb_new_families_v1.mjs';
export const contract=JSON.parse(fs.readFileSync(new URL('../../contracts/MLB_F7_STABILITY_BLOCK_V1.json',import.meta.url)));
export const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const names=contract.source_models;
export function wilson(w,n){if(!n)return null;const z=1.959963984540054,p=w/n;return (p+z*z/(2*n)-z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n)))/(1+z*z/n);}
// Integer-shape Beta CDF uses its binomial-tail identity, avoiding external numerical dependencies.
export function betaLower(w,n,q=.025){if(!n)return null;const a=w+1,N=n+1;const cdf=x=>{const terms=[];let logChoose=0;for(let k=0;k<=N;k++){if(k>=a)terms.push(logChoose+k*Math.log(x)+(N-k)*Math.log1p(-x));if(k<N)logChoose+=Math.log(N-k)-Math.log(k+1);}const m=Math.max(...terms);return Math.exp(m)*terms.reduce((s,v)=>s+Math.exp(v-m),0);};let lo=0,hi=1;for(let i=0;i<60;i++){const mid=(lo+hi)/2;if(cdf(mid)<q)lo=mid;else hi=mid;}return (lo+hi)/2;}
export function robustness(predictions){
 const m=metrics(predictions,'ML'),monthly={};for(const r of predictions){const month=r.game_date.slice(0,7);monthly[month]??={eligible:0,selected:0,n:0,wins:0,losses:0,pushes:0};const v=monthly[month];v.eligible++;if(r.ml_side===null)continue;v.selected++;if(r.truth==='DRAW')v.pushes++;else{v.n++;if(r.ml_side===r.truth)v.wins++;else v.losses++;}}
 for(const v of Object.values(monthly))v.accuracy=v.n?v.wins/v.n:null;
 const represented=Object.entries(monthly).filter(([,v])=>v.selected),lomo=Object.fromEntries(represented.map(([month,v])=>[month,{n:m.n-v.n,wins:m.wins-v.wins,accuracy:m.n>v.n?(m.wins-v.wins)/(m.n-v.n):null}])),accuracies=Object.values(lomo).map(v=>v.accuracy),minN=represented.length?Math.min(...represented.map(([,v])=>v.n)):null,topShare=m.selected?represented.map(([,v])=>v.selected).sort((a,b)=>b-a).slice(0,2).reduce((a,b)=>a+b,0)/m.selected:null,lower=wilson(m.wins,m.n),leaveWorst=accuracies.length&&accuracies.every(v=>v!==null)?Math.min(...accuracies):null,g=contract.additional_robustness_policy;
 return {...m,monthly_all:monthly,minimum_month_n:minN,represented_months:represented.length,leave_one_month_out:lomo,leave_one_month_out_min_accuracy:leaveWorst,wilson_95_lower:lower,beta_uniform_95_lower:betaLower(m.wins,m.n),top_two_month_selected_share:topShare,robust_gate_pass:m.development_gate_pass&&minN>=g.min_selected_month_n&&leaveWorst!==null&&leaveWorst>=g.min_leave_one_month_out_accuracy&&topShare<=g.max_top_two_month_selected_share&&lower>=g.min_wilson_95_two_sided_lower};
}
export function join(sources){
 const maps=names.map(name=>{const map=new Map();for(const r of sources[name]){assert(Number.isSafeInteger(r.game_pk)&&r.game_pk>0&&!map.has(r.game_pk),'IDENTITY');assert(/^(2025|2026)-/.test(r.game_date)&&r.game_date<=contract.max_date,'DATE');const p=r.probabilities;assert(['HOME','AWAY','DRAW'].every(k=>Number.isFinite(p[k])&&p[k]>=0)&&Math.abs(p.HOME+p.AWAY+p.DRAW-1)<1e-8&&p.HOME+p.AWAY>0,'PROBABILITY');assert(['HOME','AWAY','DRAW'].includes(r.truth),'TRUTH');map.set(r.game_pk,r);}return map;});
 const out=[];for(const [id,r]of maps[0]){if(!maps.every(m=>m.has(id)))continue;const rows=maps.map(m=>m.get(id));assert(rows.every(x=>x.game_date===r.game_date&&x.truth===r.truth&&x.baseline_ml===r.baseline_ml),'JOIN_CONFLICT');const ps=rows.map(x=>x.probabilities.HOME/(x.probabilities.HOME+x.probabilities.AWAY)),p=ps.reduce((a,b)=>a+b,0)/4;out.push({game_pk:id,game_date:r.game_date,truth:r.truth,baseline_ml:r.baseline_ml,source_home_probabilities:ps,p_home:p,side:p>=.5?'HOME':'AWAY',confidence:Math.max(p,1-p)});}return out.sort((a,b)=>a.game_date.localeCompare(b.game_date)||a.game_pk-b.game_pk);
}
const bin=p=>Math.min(4,Math.floor((p-.5)*10+1e-12));
export function conformal(history,r){const cal=history.slice(-300),pvalues={};if(cal.length<300)return {side:null,reason:'CALIBRATION_N'};for(const label of ['HOME','AWAY']){const group=cal.filter(x=>x.truth===label);if(group.length<100)return {side:null,reason:'CALIBRATION_CLASS_N'};const score=label==='HOME'?1-r.p_home:r.p_home;pvalues[label]=(1+group.filter(x=>(label==='HOME'?1-x.p_home:x.p_home)>=score).length)/(group.length+1);}const set=Object.keys(pvalues).filter(k=>pvalues[k]>.25);return {side:set.length===1&&set[0]===r.side&&r.confidence>=.75?r.side:null,reason:'EVALUATED',pvalues,prediction_set:set,calibration_n:cal.length,max_calibration_date:cal.at(-1).game_date};}
export function bootstrap(history,r){
 const currentMonth=r.game_date.slice(0,7),selected=history.filter(x=>x.game_date.slice(0,7)<currentMonth&&bin(x.confidence)===bin(r.confidence)),months={};for(const x of selected){const key=x.game_date.slice(0,7);months[key]??={n:0,w:0};months[key].n++;months[key].w+=Number(x.side===x.truth);}const values=Object.values(months);if(selected.length<60||values.length<3||values.some(v=>v.n<10))return {side:null,reason:'MONTH_CALIBRATION_SUPPORT',calibration_n:selected.length,months};
 let state=Number.parseInt(hash(r.game_date+':'+bin(r.confidence)).slice(0,8),16);const random=()=>{state=(Math.imul(1664525,state)+1013904223)>>>0;return state/4294967296;},samples=[];
 for(let b=0;b<1000;b++){let total=0;for(let i=0;i<values.length;i++){const v=values[Math.floor(random()*values.length)];total+=v.w/v.n;}samples.push(total/values.length);}samples.sort((a,b)=>a-b);const lower=samples[49];return {side:r.confidence>=.75&&lower>=.75?r.side:null,reason:'EVALUATED',lower,calibration_n:selected.length,months,max_calibration_date:selected.at(-1).game_date};
}
export function evaluate(sources){const rows=join(sources),predictions=Object.fromEntries(Object.keys(contract.rules).map(k=>[k,[]]));let season=null,history=[];
 for(let i=0;i<rows.length;){let j=i+1;while(j<rows.length&&rows[j].game_date===rows[i].game_date)j++;if(season!==rows[i].game_date.slice(0,4)){season=rows[i].game_date.slice(0,4);history=[];}const cache=new Map();for(const r of rows.slice(i,j)){const p=r.source_home_probabilities,agree=p.every(x=>x>.5)||p.every(x=>x<.5),strong=p.filter(x=>(r.side==='HOME'?x:1-x)>=.75).length,consensus={side:agree&&strong>=2?r.side:null,reason:agree?'AGREEMENT':'DISAGREEMENT',strong_sources:strong},conf=conformal(history,r),key=bin(r.confidence);if(!cache.has(key))cache.set(key,bootstrap(history,r));const boot={...cache.get(key)};boot.side=r.confidence>=.75&&boot.lower>=.75?r.side:null;for(const[k,detail]of Object.entries({consensus,conformal:conf,month_bootstrap:boot}))predictions[k].push({...r,ml_side:detail.side,detail});}history.push(...rows.slice(i,j).filter(r=>r.truth!=='DRAW'));i=j;}
 return {joined_games:rows.length,rules:Object.fromEntries(Object.entries(predictions).map(([k,p])=>[k,{eligible:p.length,metrics:robustness(p),predictions:p}]))};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const sources={},hashes={},prior=JSON.parse(fs.readFileSync('artifacts/research/mlb_period_poisson_v1_result.json'));for(const name of names){const path=`artifacts/research/mlb_new_families_v1_${name}`,bytes=fs.readFileSync(path+'.json.gz'),raw=zlib.gunzipSync(bytes),full=JSON.parse(raw),summary=JSON.parse(fs.readFileSync(path+'.json'));assert.equal(hash(raw),summary.full_result_sha256,'ARTIFACT_HASH');assert.equal(full.periods[7].input_sha256,prior.periods[7].input_sha256,'SOURCE_HASH');hashes[name]=hash(bytes);sources[name]=full.periods[7].predictions;}const full={contract_sha256:hash(JSON.stringify(contract)),source_artifacts_sha256:hashes,research_only:true,external_opened:false,odds_api_credits:0,...evaluate(sources)},text=JSON.stringify(full);fs.writeFileSync('artifacts/research/mlb_f7_stability_block_v1.json.gz',zlib.gzipSync(text));for(const v of Object.values(full.rules))delete v.predictions;full.full_result_sha256=hash(text);full.status=Object.values(full.rules).some(v=>v.metrics.robust_gate_pass)?'AWAITING_EXTERNAL_AUTHORIZATION':'F7_ML_RESEARCH_SATURATION_PENDING_NEW_INFORMATION';fs.writeFileSync('artifacts/research/mlb_f7_stability_block_v1.json',JSON.stringify(full,null,2)+'\n');console.log(JSON.stringify(full,null,2));}
