import fs from 'node:fs';import zlib from 'node:zlib';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
import {solve} from './evaluate_mlb_f5_opponent_count_v1.mjs';
import {hash,robustness} from './evaluate_mlb_f7_stability_block_v1.mjs';
export const contract=JSON.parse(fs.readFileSync(new URL('../../contracts/MLB_F1_KERNEL_DISTRIBUTION_V1.json',import.meta.url)));
let state=0x7135A91;const uniform=()=>{state=(Math.imul(1664525,state)+1013904223)>>>0;return (state+.5)/4294967296;},normal=()=>Math.sqrt(-2*Math.log(uniform()))*Math.cos(2*Math.PI*uniform());
export const frequencies=Array.from({length:64},()=>({w:Array.from({length:18},normal),b:2*Math.PI*uniform()}));
export function featureMap(x){assert.equal(x.length,18);return[1,...frequencies.map(f=>Math.sqrt(2/64)*Math.cos(f.b+f.w.reduce((s,w,i)=>s+w*x[i],0)))];}
const cell=(s,a)=>3*Math.min(s,2)+Math.min(a,2),sigmoid=x=>1/(1+Math.exp(-Math.max(-30,Math.min(30,x))));
export function contexts(input){const rows=[...input].sort((a,b)=>a[2].localeCompare(b[2])||a[1]-b[1]),ids=new Set();for(const r of rows){assert(r.length===11&&[2025,2026].includes(r[0])&&r[2].startsWith(String(r[0]))&&r[2]<=contract.max_date,'DATE');assert(Number.isSafeInteger(r[1])&&r[1]>0&&!ids.has(r[1]),'IDENTITY');ids.add(r[1]);assert(r[7]<r[2]&&/F1(?:_|$)/.test(r[8])&&r[9]===true&&r[10]==='HISTORICAL_SEEN_DEVELOPMENT','LINEAGE');assert(r[5]&&r[6]&&r[5]!==r[6]&&[r[3],r[4]].every(x=>Number.isSafeInteger(x)&&x>=0),'OUTCOME');}
 let year=null,n=0,league=Array(9).fill(0),teams=new Map(),wins=[0,0],lastDate=null;const out=[];for(let i=0;i<rows.length;){let j=i+1;while(j<rows.length&&rows[j][2]===rows[i][2])j++;if(year!==rows[i][0]){year=rows[i][0];n=0;league=Array(9).fill(0);teams=new Map();wins=[0,0];lastDate=null;}for(const r of rows.slice(i,j)){const h=teams.get(r[5])??[],a=teams.get(r[6])??[];if(n<300||Math.min(h.length,a.length)<20)continue;const histogram=t=>Array.from({length:9},(_,k)=>Math.sqrt((t.filter(v=>v===k).length+10*league[k]/(2*n))/(t.length+10))),x=[...histogram(h),...histogram(a)];out.push({game_pk:r[1],game_date:r[2],representation:x,features:featureMap(x),truth:r[3]>r[4]?'HOME':r[3]<r[4]?'AWAY':'DRAW',baseline_ml:wins[0]>=wins[1]?'HOME':'AWAY',max_feature_history_date:lastDate});}
 for(const r of rows.slice(i,j)){n++;if(r[3]>r[4])wins[0]++;if(r[3]<r[4])wins[1]++;for(const[t,s,a]of [[r[5],r[3],r[4]],[r[6],r[4],r[3]]]){const k=cell(s,a),history=teams.get(t)??[];league[k]++;history.push(k);if(history.length>30)history.shift();teams.set(t,history);}}lastDate=rows[i][2];i=j;}return out;
}
export function fit(rows){assert(rows.length>=250&&rows.every(r=>r.truth!=='DRAW'),'TRAINING');const d=65,w=Array(d).fill(0),home=rows.filter(r=>r.truth==='HOME').length;w[0]=Math.log((home+1)/(rows.length-home+1));let maxStep=Infinity,iterations=0;
 for(let epoch=0;epoch<50;epoch++){const g=w.map((v,k)=>-(k?1:.01)*v),H=Array.from({length:d},(_,i)=>Array.from({length:d},(_,j)=>i===j?(i?1:.01):0));for(const r of rows){const x=r.features,p=sigmoid(w.reduce((s,v,i)=>s+v*x[i],0)),res=Number(r.truth==='HOME')-p,h=p*(1-p);for(let i=0;i<d;i++){g[i]+=res*x[i];for(let j=0;j<=i;j++)H[i][j]+=h*x[i]*x[j];}}for(let i=0;i<d;i++)for(let j=0;j<i;j++)H[j][i]=H[i][j];const step=solve(H,g);maxStep=Math.max(...step.map(Math.abs));for(let i=0;i<d;i++)w[i]+=Math.max(-.5,Math.min(.5,step[i]));iterations++;if(maxStep<1e-8)break;}
 return {weights:w,training_n:rows.length,max_training_date:rows.at(-1).game_date,iterations,max_final_step:maxStep,converged:maxStep<=1e-6};
}
export function probability(model,x){return sigmoid(model.weights.reduce((s,w,i)=>s+w*x[i],0));}
export function evaluate(input){const rows=contexts(input),predictions=[],fits=[],exclusions={no_fit:0,nonconvergence:0};let season=null,month=null,history=[],model=null;for(let i=0;i<rows.length;){let j=i+1;while(j<rows.length&&rows[j].game_date===rows[i].game_date)j++;const y=rows[i].game_date.slice(0,4),m=rows[i].game_date.slice(0,7);if(y!==season){season=y;month=null;history=[];model=null;}if(m!==month){month=m;model=history.length>=250?fit(history):null;if(model)fits.push({fit_date:rows[i].game_date,...model});}for(const r of rows.slice(i,j)){if(!model){exclusions.no_fit++;continue;}if(!model.converged){exclusions.nonconvergence++;continue;}const p=probability(model,r.features);predictions.push({...r,p_home:p,ml_side:p>=.75?'HOME':p<=.25?'AWAY':null,max_training_date:model.max_training_date});}history.push(...rows.slice(i,j).filter(r=>r.truth!=='DRAW'));i=j;}return {source_rows:input.length,feature_contexts:rows.length,eligible:predictions.length,exclusions,metrics:robustness(predictions),fits,predictions};}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const source=JSON.parse(zlib.gunzipSync(fs.readFileSync('artifacts/research/mlb_new_families_v1_source.json.gz')))[1],prior=JSON.parse(fs.readFileSync('artifacts/research/mlb_period_poisson_v1_result.json')),input_sha256=hash(JSON.stringify([...source].sort((a,b)=>a[2].localeCompare(b[2])||a[1]-b[1])));assert.equal(input_sha256,prior.periods[1].input_sha256,'SOURCE_HASH');const full={architecture:contract.architecture,contract_sha256:hash(JSON.stringify(contract)),frequencies_sha256:hash(JSON.stringify(frequencies)),input_sha256,research_only:true,external_opened:false,odds_api_credits:0,...evaluate(source)},text=JSON.stringify(full);fs.writeFileSync('artifacts/research/mlb_f1_kernel_distribution_v1.json.gz',zlib.gzipSync(text));delete full.predictions;delete full.fits;full.full_result_sha256=hash(text);full.status=full.metrics.development_gate_pass?'AWAITING_EXTERNAL_AUTHORIZATION':'FAIL';fs.writeFileSync('artifacts/research/mlb_f1_kernel_distribution_v1.json',JSON.stringify(full,null,2)+'\n');console.log(JSON.stringify(full,null,2));}
