import test from 'node:test';import assert from 'node:assert/strict';
import {evaluate,join,robustness,wilson,betaLower,conformal,contract} from './evaluate_mlb_f7_stability_block_v1.mjs';
const rows=Array.from({length:1400},(_,i)=>({game_pk:i+1,game_date:new Date(Date.UTC(2025,1,1+Math.floor(i/6))).toISOString().slice(0,10),probabilities:{HOME:.8,AWAY:.15,DRAW:.05},truth:i%4===0?'AWAY':'HOME',baseline_ml:'HOME'}));
const sources=Object.fromEntries(contract.source_models.map(k=>[k,structuredClone(rows)]));
test('F7 stability rules are invariant to own-date/future labels and source ordering',()=>{const a=evaluate(sources),changed=structuredClone(sources),date=rows[1100].game_date;for(const rs of Object.values(changed))for(const r of rs)if(r.game_date>=date)r.truth='AWAY';const b=evaluate(changed);for(const k of Object.keys(a.rules)){const strip=xs=>xs.filter(r=>r.game_date<=date).map(({truth,...r})=>r);assert.deepEqual(strip(a.rules[k].predictions),strip(b.rules[k].predictions));}assert.deepEqual(evaluate(Object.fromEntries(Object.entries(sources).map(([k,v])=>[k,[...v].reverse()]))),a);});
test('joins reject duplicate IDs and conflicting source dates/outcomes',()=>{const a=structuredClone(sources);a.kalman.push(a.kalman[0]);assert.throws(()=>join(a),/IDENTITY/);const b=structuredClone(sources);b.isotonic[0].truth='DRAW';assert.throws(()=>join(b),/JOIN_CONFLICT/);});
test('Wilson and Beta bounds match analytic values and nonempty support',()=>{assert.equal(wilson(0,0),null);assert(Math.abs(wilson(5,10)-.236593090512564)<1e-12);assert(Math.abs(betaLower(10,10)-Math.pow(.025,1/11))<1e-10);assert(Math.abs(betaLower(0,10)-(1-Math.pow(.975,1/11)))<1e-10);});
test('LOMO and concentration preserve bad singleton month, pushes and empty months',()=>{const p=[...Array.from({length:20},(_,i)=>({game_date:'2025-04-01',truth:'HOME',ml_side:'HOME',baseline_ml:'HOME'})),{game_date:'2025-05-01',truth:'AWAY',ml_side:'HOME',baseline_ml:'HOME'},{game_date:'2025-06-01',truth:'DRAW',ml_side:'HOME',baseline_ml:'HOME'},{game_date:'2025-07-01',truth:'HOME',ml_side:null,baseline_ml:'HOME'}],m=robustness(p);assert.equal(m.n,21);assert.equal(m.pushes,1);assert.equal(m.minimum_month_n,0);assert.equal(m.monthly_all['2025-07'].selected,0);assert.equal(m.leave_one_month_out['2025-04'].accuracy,0);assert.equal(m.top_two_month_selected_share,21/22);assert.equal(m.robust_gate_pass,false);});
test('conformal p-values use exact class-conditional plus-one rank and reset seasons',()=>{const history=Array.from({length:300},(_,i)=>({truth:i%2?'HOME':'AWAY',p_home:i%2?.9:.1,game_date:'2025-05-01'})),r={side:'HOME',confidence:.9,p_home:.9},v=conformal(history,r);assert.equal(v.pvalues.HOME,1);assert.equal(v.pvalues.AWAY,1/151);assert.equal(v.side,'HOME');const next={...rows[0],game_pk:99999,game_date:'2026-03-25'},s=Object.fromEntries(Object.entries(sources).map(([k,v])=>[k,[...v,next]])),out=evaluate(s);assert.equal(out.rules.conformal.predictions.at(-1).detail.reason,'CALIBRATION_N');});
