import test from 'node:test';
import assert from 'node:assert/strict';
import {evaluate,cholesky,classify} from './evaluate_mlb_period_qda_v1.mjs';
import fs from 'node:fs';import zlib from 'node:zlib';import crypto from 'node:crypto';
const rows=Array.from({length:1200},(_,i)=>{const d=new Date(Date.UTC(2025,2,1+Math.floor(i/5))).toISOString().slice(0,10);return [2025,100000+i,d,i%3===0?2:i%3===1?0:1,i%3===0?0:i%3===1?2:1,'H'+i%5,'A'+i%5,new Date(Date.parse(d)-86400000).toISOString().slice(0,10),'EXACT_F7',true,'HISTORICAL_SEEN_DEVELOPMENT'];});
const forecast=ps=>ps.map(({truth,...p})=>p);
test('QDA immutable artifacts reconcile all decisions, coverage, monthly gates and input hashes',()=>{
 const s=JSON.parse(fs.readFileSync('artifacts/research/mlb_period_qda_v1_result.json')),f=JSON.parse(zlib.gunzipSync(fs.readFileSync('artifacts/research/mlb_period_qda_v1_result.json.gz'))),prior=JSON.parse(fs.readFileSync('artifacts/research/mlb_period_poisson_v1_result.json'));
 assert.equal(s.full_result_sha256,crypto.createHash('sha256').update(JSON.stringify(f)).digest('hex'));assert.equal(f.external_opened,false);assert.equal(f.odds_api_credits_consumed,0);
 for(const [p,v] of Object.entries(f.periods)){assert.equal(v.input_sha256,prior.periods[p].input_sha256);assert.equal(v.source_rows,v.eligible+v.excluded_history+v.excluded_training);assert.equal(v.predictions.length,v.eligible);
 for(const r of v.predictions){assert(Object.values(r.probabilities).every(Number.isFinite));assert(Number.isFinite(r.ml_home_conditional));assert(Math.abs(Object.values(r.probabilities).reduce((a,b)=>a+b,0)-1)<1e-12);assert.equal(r.ml_side,r.ml_home_conditional>=.75?'HOME':r.ml_home_conditional<=.25?'AWAY':null);const best=Object.entries(r.probabilities).sort((a,b)=>b[1]-a[1])[0];assert.equal(r.threeway_side,best[1]>=.75?best[0]:null);}
 for(const [market,key] of [['ML','ml_side'],['3WAY','threeway_side']]){const m=v.markets[market],sel=v.predictions.filter(r=>r[key]!==null),dec=sel.filter(r=>market!=='ML'||r.truth!=='DRAW'),months={};for(const r of dec){const d=r.game_date.slice(0,7);months[d]??=[];months[d].push(r[key]===r.truth);}const wins=dec.filter(r=>r[key]===r.truth).length,worst=dec.length?Math.min(...Object.values(months).map(rs=>rs.filter(Boolean).length/rs.length)):null;assert.equal(m.selected,sel.length);assert.equal(m.wins,wins);assert.equal(m.losses,dec.length-wins);assert.equal(m.pushes,sel.length-dec.length);assert.equal(m.accuracy,dec.length?wins/dec.length:null);assert.equal(m.coverage,sel.length/v.eligible);assert.equal(m.worst_month_accuracy,worst);assert.equal(m.development_gate_pass,m.accuracy!==null&&m.accuracy>=.75&&dec.length>=60&&Object.keys(months).length>=5&&worst>=.65);assert.deepEqual(s.periods[p].markets[market],m);}
 }
});
test('QDA predicts before own-date outcomes, order independent, season reset',()=>{const b=evaluate(rows,7),mut=structuredClone(rows),day=rows[900][2];assert(b.predictions.length>100);for(const r of mut)if(r[2]===day){r[3]=11;r[4]=0;}const m=evaluate(mut,7);assert.deepEqual(forecast(b.predictions.filter(r=>r.game_date<=day)),forecast(m.predictions.filter(r=>r.game_date<=day)));assert.notDeepEqual(forecast(b.predictions.filter(r=>r.game_date>day)),forecast(m.predictions.filter(r=>r.game_date>day)));assert.deepEqual(evaluate([...rows].reverse(),7),b);const next=[...rows[0]];next[0]=2026;next[1]=999999;next[2]='2026-03-25';next[7]='2026-03-24';assert.equal(evaluate([...rows,next],7).eligible,b.eligible);});
test('QDA rejects duplicates, same-day cutoff, external and wrong periods',()=>{assert.throws(()=>evaluate([...rows,rows[0]],7),/DUPLICATE/);assert.throws(()=>evaluate(rows,5),/LINEAGE/);const b=structuredClone(rows);b[0][7]=b[0][2];assert.throws(()=>evaluate(b,7),/CUTOFF/);b[0][0]=2026;b[0][2]='2026-09-20';assert.throws(()=>evaluate(b,7),/DATE/);});
test('Gaussian normalization and Cholesky match independent diagonal case',()=>{const cov=[[4,0,0,0],[0,9,0,0],[0,0,16,0],[0,0,0,25]],l=cholesky(cov);assert.deepEqual(l,[[2,0,0,0],[0,3,0,0],[0,0,4,0],[0,0,0,5]]);const p=classify([0,0,0,0],Object.fromEntries(['HOME','AWAY','DRAW'].map((c,i)=>[c,{mean:[0,0,0,0],l,prior:[.2,.3,.5][i]}])));for(const [c,n] of Object.entries({HOME:.2,AWAY:.3,DRAW:.5}))assert(Math.abs(p[c]-n)<1e-12);});
