import test from 'node:test';import assert from 'node:assert/strict';import {evaluate} from './evaluate_mlb_period_bayesian_mixture_v1.mjs';
import fs from 'node:fs';import zlib from 'node:zlib';import crypto from 'node:crypto';
const p=[{HOME:.8,AWAY:.1,DRAW:.1},{HOME:.2,AWAY:.6,DRAW:.2},{HOME:.5,AWAY:.25,DRAW:.25}];
const fixture=()=>p.map(probabilities=>Array.from({length:12},(_,i)=>({game_pk:i+1,game_date:`2025-04-${String(1+Math.floor(i/2)).padStart(2,'0')}`,probabilities,truth:i%2?'AWAY':'HOME'})));
const forecasts=r=>r.predictions.map(({truth,...x})=>x);
test('mixture weights equal independent Bayes likelihood update and batch same dates',()=>{const x=evaluate(fixture());assert.deepEqual(x.predictions[0].weights,[1/3,1/3,1/3]);assert.deepEqual(x.predictions[0].weights,x.predictions[1].weights);const v=p.map(q=>q.HOME*q.AWAY),s=v.reduce((a,b)=>a+b,0);x.predictions[2].weights.forEach((w,i)=>assert(Math.abs(w-v[i]/s)<1e-12));});
test('own-date labels do not change own or earlier forecasts; future labels only update future weights',()=>{const f=fixture(),a=evaluate(f),b=structuredClone(f);for(const rs of b)for(const r of rs)if(r.game_date==='2025-04-03')r.truth='DRAW';const c=evaluate(b);assert.deepEqual(forecasts(a).filter(r=>r.game_date<='2025-04-03'),forecasts(c).filter(r=>r.game_date<='2025-04-03'));assert.notDeepEqual(forecasts(a).filter(r=>r.game_date>'2025-04-03'),forecasts(c).filter(r=>r.game_date>'2025-04-03'));assert.deepEqual(evaluate(f.map(rs=>[...rs].reverse())),a);});
test('season reset and identity, truth, date and probability guards',()=>{const f=fixture();f.forEach(rs=>rs.push({...rs[0],game_pk:99,game_date:'2026-04-01'}));assert.deepEqual(evaluate(f).predictions.at(-1).weights,[1/3,1/3,1/3]);const dup=fixture();dup[0].push(dup[0][0]);assert.throws(()=>evaluate(dup),/DUPLICATE/);const future=fixture();future[0][0].game_date='2026-09-20';assert.throws(()=>evaluate(future),/DATE/);const bad=fixture();bad[0][0].truth='DRAW';assert.throws(()=>evaluate(bad),/TRUTH_MISMATCH/);});
test('saved mixture fully replays frozen expert forecasts and independent decision arithmetic',()=>{
 const hash=x=>crypto.createHash('sha256').update(x).digest('hex'),bytes=zlib.gunzipSync(fs.readFileSync('artifacts/research/mlb_period_bayesian_mixture_v1_result.json.gz')),full=JSON.parse(bytes),summary=JSON.parse(fs.readFileSync('artifacts/research/mlb_period_bayesian_mixture_v1_result.json'));
 assert.equal(hash(bytes),summary.full_result_sha256);const sources=['poisson','qda','empirical_convolution'].map((name,i)=>{const b=fs.readFileSync(`artifacts/research/mlb_period_${name}_v1_result.json.gz`);assert.equal(hash(b),full.expert_artifact_sha256[i]);return JSON.parse(zlib.gunzipSync(b));});
 for(const [period,v]of Object.entries(full.periods)){assert(sources.every(s=>s.periods[period].input_sha256===v.input_sha256));const {input_sha256,...saved}=v;assert.deepEqual(evaluate(sources.map(s=>s.periods[period].predictions)),saved);for(const [m,k] of [['ML','ml_side'],['3WAY','threeway_side']]){const sel=v.predictions.filter(r=>r[k]!==null),dec=sel.filter(r=>m!=='ML'||r.truth!=='DRAW'),wins=dec.filter(r=>r[k]===r.truth).length;assert.equal(v.markets[m].wins,wins);assert.equal(v.markets[m].losses,dec.length-wins);assert.equal(v.markets[m].pushes,sel.length-dec.length);assert.equal(v.markets[m].coverage,sel.length/v.eligible);assert.deepEqual(v.markets[m],summary.periods[period].markets[m]);} }
 assert.equal(full.external_opened,false);assert.equal(full.odds_api_credits,0);
});
